apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
    - name: my-container
      image: nginx
      resources:
        requests:
          memory: '50Mi'
          cpu: '50m'
        limits:
          memory: '100Mi'
          cpu: '100m'

